name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/chen08209/FlClash.git
          git fetch upstream

      - name: Merge upstream/main
        run: |
          git checkout main
          git merge --allow-unrelated-histories upstream/main

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.SYNC_UPSTREAM }}
          branch: main
